// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsjyzsxaahadydlnbgwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzanl6c3hhYWhhZHlkbG5iZ3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTEyNDYsImV4cCI6MjA3NDU2NzI0Nn0.ueVidteXFoRyvcxli4AR8a7B2yKDqZoFisiGIb5u8gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});